### PR TITLE
Fix decoding of heterogeneus arrays

### PR DESCRIPTION
**Pull request by ziopio**
When performing method calls, InputArguments is an array of eterogeneus elements.
~~In this case and in the case these are builtin, the type-id is encoded before each element.~~
Second approach is to insert variant as default type for structure fields at the parsing step.

### CODE REVIEW

**Comment by ziopio** [comment]
@sylane not sure if this is the right way to integrate this "fix"

**Comment by sylane** [comment]
I don't think this is the correct fix, the decode_type is not mean to decode any value, and neither the OPCUA format generically support decoding a valuation without type information. This looks like a local special case, so the type handling should be done in the place it is special, not in the generic type decoding function. I am not sure about it, but if the special case is in arrays that can have variable types, the decoding of the type byte should be there.

**Comment by ziopio** [comment]
@sylane not sure if is the best place but now i can actually encode and decode those generic arrays

**Review by sylane — APPROVED** [review]
Looks good !

**Pull request merged**
